site_name: LIT Year 3 - Advanced Digital Game Programming
site_url: https://joeaoregan.github.io/Alien-Attack/

docs_dir: docs
site_dir: site

repo_url: https://github.com/joeaoregan/LIT-Yr3-AdvancedDigitalGameProgramming
repo_name: GitHub

theme:
  name: material
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        primary: 'blue'
        accent: 'light blue'

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  favicon: images/favicon.ico
  icon:
    admonition:
      note: material/alpha-j
      success: material/alpha-j
      warning: material/alpha-j
      danger: material/alpha-j
  logo: images/logo.png

        
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - navigation.footer
    - navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - SDL Setup:
    - Overview: sdl-setup/index.md
  - Architecture:
    - Overview: architecture/index.md
    - State Machine: architecture/state-machine.md
    - Object Factory: architecture/object-factory.md
    - Level Parser: architecture/level-parser.md
    - Play State: architecture/play-state.md
    - Collision Manager: architecture/collision-manager.md
    - Input Handler: architecture/input-handler.md
    - Bullet Handler: architecture/bullet-handler.md
    - Heads Up Display: architecture/hud.md
    - Mini Map: architecture/mini-map.md
    - Animated Graphics: architecture/animated-graphics.md
  - Game Objects:
    - Overview: game-objects/index.md
    - Player: game-objects/player.md
    - Enemy: game-objects/enemy.md
    - Bullet: game-objects/bullet.md
    - Glider: game-objects/glider.md
    - Shot Glider: game-objects/shotglider.md
    - Angry Glider: game-objects/angryglider.md
    - Pounder: game-objects/pounder.md
    - Eskeletor: game-objects/eskeletor.md
    - Level 1 Boss: game-objects/level1boss.md
    - Power Up: game-objects/powerup.md
    - Roof Turret: game-objects/roof-turret.md
    - Shooter Object: game-objects/shooter.md
  - States:
    - Overview: states/index.md
    - Menu: states/main-menu.md
    - Game: states/game.md
    - Play: states/play.md
    - Pause: states/pause.md
    - Level Complete: states/level-complete.md
    - Game Over: states/game-over.md
    - Settings: states/settings.md
    - High Scores: states/high-score.md
    - Instructions: states/instructions.md
    - Enter Name: states/enter-name.md
    - Level Objective: states/level-objective.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/joeaoregan/LIT-Yr3-AdvancedDigitalGameProgramming

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascript/mermaid-init.js